// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHvxH3LccCNL3zjyW3EUnKabg760nBu-8',
    appId: '1:923954671239:web:c4af93fe1c50e95a7c1222',
    messagingSenderId: '923954671239',
    projectId: 'togetherlistapp',
    authDomain: 'togetherlistapp.firebaseapp.com',
    storageBucket: 'togetherlistapp.appspot.com',
    measurementId: 'G-VG2T182VYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgDwMtLLoAJ20OVqX7t21u-J0tniJ2LZg',
    appId: '1:923954671239:android:ca46d18855df6d957c1222',
    messagingSenderId: '923954671239',
    projectId: 'togetherlistapp',
    storageBucket: 'togetherlistapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB82aCXmQiD8T7YAHc-lh9fVeQzB3TTrds',
    appId: '1:923954671239:ios:b54dd372765d38f37c1222',
    messagingSenderId: '923954671239',
    projectId: 'togetherlistapp',
    storageBucket: 'togetherlistapp.appspot.com',
    androidClientId: '923954671239-12tpq73bklu98i5ib2rfohfges0u748m.apps.googleusercontent.com',
    iosClientId: '923954671239-kbqdm5l7sp1kslsf1gpt0nv9bbnirn2d.apps.googleusercontent.com',
    iosBundleId: 'com.totech.togethershoplist',
  );
}
